import Head from "next/head";

import {Button} from "~/components/ui/button"
import {Textarea} from "~/components/ui/textarea";
import {Avatar, AvatarFallback, AvatarImage} from "~/components/ui/avatar";
import {Card, CardContent, CardHeader, CardTitle} from "~/components/ui/card";
import {api} from "~/utils/api";
import { Input } from "~/components/ui/input"
import {Label} from "@radix-ui/react-label";
import {useState} from "react";


export default function Home() {

    const questions = api.pteQuestion.list.useQuery();

    const [questionNo,setQuestionNo] = useState("")
    const [title,setTitle] = useState("")
    const [type,setType] = useState("")
    const [content,setContent] = useState("")




    const {mutate} = api.pteQuestion.create.useMutation({
        onSettled: async () => {
            await questions.refetch().then().catch();
        }
    });


    return (
        <>
            <Head>
                <title>PTE学习资料</title>
                <meta name="description" content="Generated by create-t3-app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className="flex flex-col justify-center w-1/2 mx-auto">
                <h4 className="scroll-m-20 text-xl font-semibold tracking-tight text-center mt-2">
                    PTE Question
                </h4>
                <div className="flex justify-end">
                    <Avatar>
                        <AvatarImage src="https://github.com/shadcn.png" alt="@shadcn" />
                        <AvatarFallback>CN</AvatarFallback>
                    </Avatar>
                </div>

                <div className="mt-2">
                    <Card>
                        <CardHeader>
                            <CardTitle>Create Question</CardTitle>
                        </CardHeader>
                        <CardContent>
                            <div className="grid gap-4 mt-2">
                                <Label htmlFor="questionNo">No</Label>
                                <Input className="w-full" value={questionNo} onChange={(e) => setQuestionNo(e.target.value)} />
                                <Label htmlFor="type">Type</Label>
                                <Input className="w-full" value={type} onChange={(e) => setType(e.target.value)} />
                                <Label htmlFor="title">Title</Label>
                                <Input className="w-full" value={title} onChange={(e) => setTitle(e.target.value)} />
                                <Label htmlFor="content">Content</Label>
                                <Textarea className="w-full" value={content} onChange={(e) => setContent(e.target.value)}/>

                                <Button onClick={() => {
                                    mutate({
                                        questionNo: questionNo,
                                        type:type,
                                        title:title,
                                        content:content
                                    })
                                    setQuestionNo("")
                                    setTitle("")
                                    setType("")
                                    setContent("")
                                }
                                }>
                                    提交
                                </Button>
                            </div>
                        </CardContent>
                    </Card>
                </div>

                <div className="mt-2">
                    {questions.data?.map((question) => (
                        <Card key={question.id}>
                            <CardHeader>
                                <CardTitle>{question.title}</CardTitle>
                            </CardHeader>
                            <CardContent>
                                <p className="leading-7 [&:not(:first-child)]:mt-6">
                                    {question.content}
                                </p>
                            </CardContent>
                        </Card>
                    ))}
                </div>
            </main>
        </>
    );
}
