import Head from "next/head";

import {Button} from "~/components/ui/button"
import {Textarea} from "~/components/ui/textarea";
import {Table, TableBody, TableCell, TableHead, TableHeader, TableRow,} from "~/components/ui/table"
import {Avatar, AvatarFallback, AvatarImage} from "~/components/ui/avatar";
import {Card, CardContent, CardHeader, CardTitle} from "~/components/ui/card";
import {useRef} from "react";


export default function Home() {

    return (
        <>
            <Head>
                <title>PTE学习资料</title>
                <meta name="description" content="Generated by create-t3-app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className="flex flex-col justify-center w-1/2 mx-auto">
                <h4 className="scroll-m-20 text-xl font-semibold tracking-tight text-center mt-2">
                    学习资料
                </h4>
                <div className="flex justify-end">
                    <Avatar>
                        <AvatarImage src="https://github.com/shadcn.png" alt="@shadcn" />
                        <AvatarFallback>CN</AvatarFallback>
                    </Avatar>
                </div>
                <div className="mt-2">
                    <Card>
                        <CardHeader>
                            <CardTitle> World Map of Happiness </CardTitle>
                        </CardHeader>
                        <CardContent>
                            <p className="leading-7 [&:not(:first-child)]:mt-6">
                                Bhutan used to be one of the most isolated nations in the world. Developments including direct international flights, the Internet, mobile phone networks, and cable television have increasingly modernised the urban areas of the country. Bhutan has balanced modernization with its ancient culture and traditions under the guiding philosophy of Gross National Happiness"GNH". Rampant destruction of the environment has been avoided. The government takes great measures to preserve the nation's traditional culture, identity and the environment. In 2006, Business Week magazine rated Bhutan the happiest country in Asia and the eighth- happiest in the world, citing a global survey conducted by the University of Leicester in 2006 called the"World Map of Happiness".
                            </p>
                        </CardContent>
                    </Card>
                    <Card>
                        <CardHeader>
                            <CardTitle>  How world works  </CardTitle>
                        </CardHeader>
                        <CardContent>
                            <p className="leading-7 [&:not(:first-child)]:mt-6">
                                Throughout the 18 th century, mathematicians, scientists and philosophers researched, discussed, and published their investigations into how the world worked, while engineers and inventors developed new and successful machines and processes. The latest theories inspired greater invention, and more technology encouraged theoretical scientists to make further discoveries in medicine, biology, mechanics, physics, and chemistry. By 1800, the new machines had brought revolutionary changes to the workplace, transportation and communications, and eventually to the home. Some of these inventions simply made it easier to produce things on a large scale such as textile machines and foundries, which produced large quantities of cloth and metal objects quickly and cheaply. But some inventions brought completely new possibilities such as the first batteries, steamboats, and locomotives. It would take decades for some of these inventions to make a big impact on the world. Yet their creation, and the sheer amount of imagination and risk- taking involved, marked the beginning of a modern, global, technologically based economy of the kind that we live in today.
                            </p>
                        </CardContent>
                    </Card>
                </div>


            </main>
        </>
    );
}
