import Head from "next/head";

import {Button} from "~/components/ui/button"
import {Textarea} from "~/components/ui/textarea";
import {Table, TableBody, TableCell, TableHead, TableHeader, TableRow,} from "~/components/ui/table"
import {Avatar, AvatarFallback, AvatarImage} from "~/components/ui/avatar";
import {Card, CardContent, CardHeader, CardTitle} from "~/components/ui/card";


export default function Home() {

    const invoices = [
        {
            invoice: "INV001",
            content: "第一个留言"
        },
        {
            invoice: "INV002",
            content: "Pending"
        },
        {
            invoice: "INV003",
            content: "Unpaid"
        },
        {
            invoice: "INV004",
            content: "Paid"
        },
        {
            invoice: "INV005",
            content: "Paid"
        },
        {
            invoice: "INV006",
            content: "Pending"
        },
        {
            invoice: "INV007",
            content: "Unpaid"
        },
    ]


    return (
        <>
            <Head>
                <title>留言板</title>
                <meta name="description" content="Generated by create-t3-app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className="flex flex-col justify-center w-1/2 mx-auto">
                <h4 className="scroll-m-20 text-xl font-semibold tracking-tight text-center mt-2">
                    留言板
                </h4>
                <div className="flex justify-end">
                    <Avatar>
                        <AvatarImage src="https://github.com/shadcn.png" alt="@shadcn" />
                        <AvatarFallback>CN</AvatarFallback>
                    </Avatar>
                </div>
                <div className="mt-2">
                    <Card>
                        <CardHeader>
                            <CardTitle>新留言</CardTitle>
                        </CardHeader>
                        <CardContent>
                            <div className="grid gap-4 mt-2">
                                <Textarea className="w-full" placeholder="留言" />
                                <Button>Send message</Button>
                            </div>
                        </CardContent>
                    </Card>
                </div>

                <div className="mt-2">
                    <Card>
                        <CardHeader>
                            <CardTitle>历史留言</CardTitle>
                        </CardHeader>
                        <CardContent>
                            <Table>
                                <TableHeader>
                                    <TableRow>
                                        <TableHead className="w-[80px]">作者</TableHead>
                                        <TableHead>留言</TableHead>
                                    </TableRow>
                                </TableHeader>
                                <TableBody>
                                    {invoices?.map((invoice) => (
                                        <TableRow key={invoice.invoice}>
                                            <TableCell>
                                                <Avatar>
                                                    <AvatarImage src="https://github.com/shadcn.png" alt="@shadcn" />
                                                    <AvatarFallback>CN</AvatarFallback>
                                                </Avatar>
                                            </TableCell>
                                            <TableCell>{invoice.content}</TableCell>
                                        </TableRow>
                                    ))}
                                </TableBody>
                            </Table>
                        </CardContent>
                    </Card>
                </div>
            </main>
        </>
    );
}
